# Generated by Django 3.2.23 on 2023-11-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone_no',
            field=models.CharField(default=0, max_length=11),
        ),
    ]
