# Generated by Django 3.2.3 on 2023-11-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_booking_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='no_of_guests',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.IntegerField(choices=[(1, '12:00 - 13:50'), (2, '14:00 - 15:50'), (3, '16:00 - 17:50'), (4, '18:00 - 19:50'), (5, '20:00 - 21:50')], default=1),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('date', 'time'), name='unique_booking'),
        ),
    ]
