# Generated by Django 3.2.3 on 2023-12-07 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_menus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menus',
            new_name='Menu',
        ),
    ]
