# Generated by Django 3.2.3 on 2023-12-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_alter_menu_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.IntegerField(choices=[(1, 'Starter'), (2, 'Main'), (3, 'Dessert'), (4, 'Side')]),
        ),
    ]
