# Generated by Django 3.2.3 on 2023-12-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_alter_menu_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.IntegerField(choices=[(1, '12:00-13:50'), (2, '14:00-15:50'), (3, '16:00-17:50'), (4, '18:00-19:50'), (5, '20:00-21:50')], default=1),
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.IntegerField(choices=[(1, 'Starter'), (2, 'Main'), (3, 'Dessert'), (4, 'Side'), (5, 'Sauce')]),
        ),
    ]
